version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5000:5000"
    volumes:
      - ./downloads:/app/downloads
      - ./processed:/app/processed

  next:
    build:
      context: learn
    ports:
      - "3000:3000"
    tty: true
